### ISSUE TITLE
amy: ADSR envelope for SINE, SAW... doesn't do Attack properly

### ISSUE THREAD

**Issue by dpwe** [shorepine/alles#59]
It looks the Attack segment goes to max amp over the first 5.8ms window, then sits there until the end of the attack segment.  It's supposed to ramp up gradually across the entire attack time.

Thus, 
```
alles.send(osc=0, bp0='100,1.0,1000,0.0,0,0.0', bp0_target=alles.TARGET_AMP)
alles.send(osc=0, freq=2000, vel=1)
```
generates a waveform like this:
![image](https://github.com/bwhitman/tulipcc/assets/552145/88f13d18-8121-49a4-9237-8f06bab5a451)

Notice how the envelope is basically rectangular for the first 100ms, before beginning its decay.

**Comment by bwhitman** [comment]
What happens if you do 

`alles.send(osc=0, bp0='0,0,100,1.0,1000,0.0,0,0.0', bp0_target=alles.TARGET_AMP)` ?
