### ISSUE TITLE
client parameter doesn't seem to work

### ISSUE THREAD

**Issue by phesterman** [shorepine/alles#76]
I now have a mesh of 4 DIY alles synths.  I've been working through the various tutorials with general success, but one thing that doesn't seem to work is when I specify a particular client.  For example, alles.drums() plays as expected on all four clients; but, alles.drums(client=2) also plays on all four clients.  Or, if I try to assign a different chord member to each client, all of the clients seem to be trying to play the complete chord (the effect actually sounds more like FM).  I also experimented with alles.mesh() on my Tulip.  Once again all 4 alles synths work correctly when addressed as a group, but the result of amy.drums(client=2) for example, is as I've described above, i.e. clients don't seem to be individually addressable and all respond.  

By the way, even though alles.sync() doesn't work (in alles.py), alles.map() works as it should on the Tulip. And on another note, the text refers to an alles_util.py script.  I can't find this anywhere.

**Comment by bwhitman** [comment]
@phesterman thanks for the report. I will look into client not working asap. `alles.sync()` is also on our short term todo list. 
`alles_util` is no longer needed and we'll clean that up as well.

**Comment by bwhitman** [comment]
Hey! Sorry for our delay. I think I've fixed this now. An Alles re-flash or OTA update should take care of this, along with a fresh copy of `alles.py` in this repo.

**Comment by phesterman** [comment]
Thanks!  I’m away from home right now, but I’ll give it a try again in a few days.

Peter


On Nov 2, 2024, at 2:57 PM, Brian Whitman ***@***.***> wrote:



Hey! Sorry for our delay. I think I've fixed this now. An Alles re-flash or OTA update should take care of this, along with a fresh copy of alles.py in this repo.
