### ISSUE TITLE
alles.volume() not working

### ISSUE THREAD

**Issue by phesterman** [shorepine/alles#80]
I was able to reflash my 4 DIY alles speakers using the latest esp-idf and the most recent versions of alles and amy.  I'm happy to report that alles.sync() and the client parameter both are working now, so thanks again for that.  In testing alles alone and with my tulip, I discovered that both alles.volume(x) and amy.volume(x) now generate errors.

**Comment by bwhitman** [comment]
Ah yeah, `amy.volume()` is an old piece of AMY that we should remove. You should use instead `amy.send(volume=X)` (or `alles.send`, it's the same thing in Alles.) I'll remove those from AMY and update docs. Great to hear client and sync work again for you!

**Comment by phesterman** [comment]
OK, thanks!
