### ISSUE TITLE
Single synth wired setup

### ISSUE THREAD

**Issue by smutax** [shorepine/alles#9]
Hi there. Great project! I wonder, would it not be possible for a single synth connected through wired midi to still produce sound? For testing purposes or just for a single synth setup. Or maybe even consider wired setup where few synths connected into a kind of cluster. Many thanks.

**Comment by bwhitman** [comment]
A single synth 'immediate mode' over wired MIDI is certainly possible. If you don't need BTLE for MIDI, you can keep the oscillators on. and if you don't need the mesh, you could turn off wifi too and set latency to 0. Would require firmware changes and more work on the MIDI mode to expose more of the features.

As far as a wired cluster, that's a bit out of scope for us, but a lot of this code would be helpful to build something like that! You could also just use a multi-MIDI out hub and directly connect as many synths as you want.

**Comment by smutax** [comment]
> A single synth 'immediate mode' over wired MIDI is certainly possible. If you don't need BTLE for MIDI, you can keep the oscillators on. and if you don't need the mesh, you could turn off wifi too and set latency to 0. Would require firmware changes and more work on the MIDI mode to expose more of the features.
> 
Thank for the quick reply. I don't suppose you could consider the above a feature request? Another thing, there is an idea of generating new FM patches on-device so to speak. Would be interesting to hear what you think about such thing, https://github.com/Nintorac/NeuralDX7, see the mention of "live.py" in there. It basically takes 8 midi cc controls from your "midi controller to control the latent variables of the model and update the parameters of your FM Synthesizer in real time." All the very best

**Comment by bwhitman** [comment]
Just in case you haven't seen https://github.com/shorepine/amy , this does that!

**Comment by smutax** [comment]
> Just in case you haven't seen https://github.com/shorepine/amy , this does that!

Thanks Brian. I'll have a look. All the best.
